# Generated by Django 4.1.5 on 2023-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_rename_productform_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
